# Site settings
title: DevJounal 
SEOTitle: Luan Cestari Blog
header-img: img/home-bg.jpg
email: luan.cestari@gmail.com
description: "Learning more about many subjects and find some tips about them | How about combine Machine Learning creating a Big Data pipeline using Streams? Or creating some cool simple projects to test a concept? Find curated links for nice new tecnology around many different languages"
keyword: "Machine Learning，Software Architecture, Software Engineer, Software Development, Software Engineering , Web, JavaScript, @BR_LuanCestari, BR_LuanCestari, luan-cestari, luan.cestari, luan"
url: "https://luan-cestari.github.io/" # your host, for absolute URL
baseurl: ""                            # for example, '/blog' if your blog hosted on 'host/blog'

# SNS settings
RSS: true
github_username:    luan-cestari
twitter_username:   BR_LuanCestari
facebook_username:  luan.cestari
linkedin_username:  luancestari

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]
# using as well: npm install simple-jekyll-search

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# Global comment feature toggle
comments: true 
# Disqus settings
disqus_username: https-luan-cestari-github-io

# Google Analytics
ga_track_id: 'UA-39948933-7'
ga_domain: luan-cestari.github.io

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Let's make a better world with software and passion"
sidebar-avatar: https://avatars2.githubusercontent.com/u/1569137?v=4&s=460

# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true